package com.ollanest.service;

import java.security.MessageDigest;
import java.security.SecureRandom;

import javax.crypto.Cipher;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

/**
 * AES-256-GCM symmetric encryption service for sensitive credential storage.
 *
 * <h3>Why this class exists</h3>
 * <p>
 * Connector API keys, SSO client secrets, and other credentials must be stored
 * in the SQLite database but must never be readable as plain text from a DB
 * dump. {@code CryptoService} encrypts those values before persistence and
 * decrypts them at runtime. It is the single encryption boundary in the
 * application — no other class calls the JCE crypto APIs directly.
 *
 * <h3>Encryption scheme</h3>
 * <p>
 * Algorithm: {@code AES/GCM/NoPadding} with a 128-bit authentication tag and a
 * 96-bit (12-byte) random IV generated by {@link SecureRandom} for every
 * encryption call. The 256-bit key is derived from the {@code encryption.key}
 * property via SHA-256 so that any passphrase length produces a valid 32-byte
 * AES key.
 *
 * <p>
 * Stored format (colon-delimited hex strings):
 * 
 * <pre>
 *   {iv_hex}:{auth_tag_hex}:{ciphertext_hex}
 * </pre>
 * 
 * This format is wire-compatible with the original Node.js
 * {@code CryptoService} implementation that Olla Nest was migrated from.
 *
 * <h3>Design notes</h3>
 * <ul>
 * <li>A fresh IV is generated per encryption call, so encrypting the same
 * plaintext twice produces different ciphertext — preventing birthday
 * attacks.</li>
 * <li>Decryption failures return an empty string rather than throwing, to
 * prevent information leakage through error messages when credentials are
 * corrupt or the key has been rotated.</li>
 * <li>The key is derived at construction time and stored as a {@code byte[]}
 * field; the raw property string is not retained after construction.</li>
 * </ul>
 *
 * <h3>Version history</h3>
 * <ul>
 * <li><b>v2026.1.0</b> — initial Java Spring Boot migration; AES-256-GCM
 * implementation compatible with the original Node.js crypto module.</li>
 * <li><b>v2026.1.4</b> — no logic changes; comprehensive JavaDoc added.</li>
 * </ul>
 *
 * @author Ashok Ram
 * @since v2026.1.0
 * @version v2026.1.4
 * @see com.ollanest.connector.BaseConnector
 * @see com.ollanest.service.SsoService
 */
@Service
public class CryptoService {

	/** GCM authentication tag length in bits (128 bits = 16 bytes). */
	private static final int GCM_TAG_BITS = 128;

	/**
	 * Shared SecureRandom for IV generation — instantiating a new SecureRandom per
	 * {@link #encryptKey} call is expensive and drains the OS entropy pool
	 * unnecessarily. SecureRandom is thread-safe and safe as a static field.
	 */
	private static final SecureRandom SECURE_RANDOM = new SecureRandom();

	/**
	 * GCM IV length in bytes (96 bits is the recommended NIST value for AES-GCM).
	 */
	private static final int GCM_IV_BYTES = 12;

	/**
	 * The 256-bit AES encryption key derived from the {@code encryption.key}
	 * application property via SHA-256. Stored as a raw byte array — the source
	 * property string is discarded after construction.
	 */
	private final byte[] key;

	/**
	 * Constructs the service and derives the 256-bit AES key from the supplied
	 * passphrase.
	 *
	 * <p>
	 * The passphrase is hashed with SHA-256 to produce a 32-byte key regardless of
	 * the original string length. The default value
	 * {@code "change-me-in-production"} is a deliberate placeholder that must be
	 * overridden in any real deployment via the {@code encryption.key} environment
	 * variable or application property.
	 *
	 * @param encryptionKey the raw passphrase injected from {@code encryption.key}
	 *                      property; defaults to {@code "change-me-in-production"}
	 * @throws RuntimeException if the JVM does not support the {@code SHA-256}
	 *                          algorithm or {@code UTF-8} encoding (should never
	 *                          happen on any compliant JVM)
	 * @since v2026.1.0
	 */
	public CryptoService(@Value("${encryption.key:change-me-in-production}") String encryptionKey) {
		try {
			MessageDigest sha256 = MessageDigest.getInstance("SHA-256");
			this.key = sha256.digest(encryptionKey.getBytes("UTF-8"));
		} catch (Exception e) {
			throw new RuntimeException("Failed to initialize CryptoService", e);
		}
	}

	// -------------------------------------------------------------------------
	// Public API
	// -------------------------------------------------------------------------

	/**
	 * Encrypts a plain-text string and returns a colon-delimited hex-encoded
	 * ciphertext.
	 *
	 * <p>
	 * Generates a fresh 96-bit random IV for each call, encrypts using
	 * {@code AES/GCM/NoPadding}, then separates the JCE-concatenated
	 * {@code ciphertext+tag} output into individual hex segments. The result has
	 * the format:
	 * 
	 * <pre>
	 *   {iv_hex}:{auth_tag_hex}:{ciphertext_hex}
	 * </pre>
	 *
	 * @param plaintext the credential or secret string to encrypt; must not be
	 *                  {@code null}
	 * @return a hex-encoded encrypted string in {@code iv:tag:ciphertext} format,
	 *         ready for storage in the database
	 * @throws RuntimeException if encryption fails (key invalid, JCE provider
	 *                          issue)
	 * @since v2026.1.0
	 */
	public String encryptKey(String plaintext) {
		try {
			byte[] iv = new byte[GCM_IV_BYTES];
			SECURE_RANDOM.nextBytes(iv);
			SecretKeySpec keySpec = new SecretKeySpec(key, "AES");
			Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
			cipher.init(Cipher.ENCRYPT_MODE, keySpec, new GCMParameterSpec(GCM_TAG_BITS, iv));
			byte[] encrypted = cipher.doFinal(plaintext.getBytes("UTF-8"));
			// JCE appends the 16-byte auth tag after the ciphertext
			int cipherLen = encrypted.length - 16;
			byte[] ciphertext = new byte[cipherLen];
			byte[] tag = new byte[16];
			System.arraycopy(encrypted, 0, ciphertext, 0, cipherLen);
			System.arraycopy(encrypted, cipherLen, tag, 0, 16);
			return toHex(iv) + ":" + toHex(tag) + ":" + toHex(ciphertext);
		} catch (Exception e) {
			throw new RuntimeException("Encryption failed", e);
		}
	}

	/**
	 * Decrypts a stored {@code iv:tag:ciphertext} hex string back to plain text.
	 *
	 * <p>
	 * Splits the stored value on {@code ":"}, decodes each hex segment, reassembles
	 * the JCE-expected {@code ciphertext+tag} byte array, and decrypts. Returns an
	 * empty string — rather than throwing — on any failure (malformed input, wrong
	 * key, corrupt tag) to prevent information leakage through exception messages.
	 *
	 * @param stored the hex-encoded {@code iv:tag:ciphertext} string from the
	 *               database; returns {@code ""} if {@code null} or blank
	 * @return the decrypted plain-text string, or {@code ""} if decryption fails
	 *         for any reason (bad format, wrong key, authentication tag mismatch)
	 * @since v2026.1.0
	 */
	public String decryptKey(String stored) {
		try {
			if (stored == null || stored.isBlank())
				return "";
			String[] parts = stored.split(":");
			if (parts.length < 3)
				return "";
			byte[] iv = fromHex(parts[0]);
			byte[] tag = fromHex(parts[1]);
			byte[] ciphertext = fromHex(parts[2]);
			// JCE GCM expects ciphertext concatenated with auth tag
			byte[] combined = new byte[ciphertext.length + tag.length];
			System.arraycopy(ciphertext, 0, combined, 0, ciphertext.length);
			System.arraycopy(tag, 0, combined, ciphertext.length, tag.length);
			SecretKeySpec keySpec = new SecretKeySpec(key, "AES");
			Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
			cipher.init(Cipher.DECRYPT_MODE, keySpec, new GCMParameterSpec(GCM_TAG_BITS, iv));
			return new String(cipher.doFinal(combined), "UTF-8");
		} catch (Exception e) {
			// Intentionally silent: corrupt/unreadable credentials should not
			// leak key or algorithm details through exception messages.
			return "";
		}
	}

	// -------------------------------------------------------------------------
	// Private helpers
	// -------------------------------------------------------------------------

	/**
	 * Converts a byte array to a lowercase hexadecimal string.
	 *
	 * @param bytes the byte array to encode; must not be {@code null}
	 * @return lowercase hex string of length {@code bytes.length * 2}
	 * @since v2026.1.0
	 */
	private String toHex(byte[] bytes) {
		StringBuilder sb = new StringBuilder(bytes.length * 2);
		for (byte b : bytes) {
			sb.append(String.format("%02x", b));
		}
		return sb.toString();
	}

	/**
	 * Decodes a lowercase hexadecimal string back to a byte array.
	 *
	 * @param hex the hex string to decode; length must be even
	 * @return the decoded byte array of length {@code hex.length() / 2}
	 * @since v2026.1.0
	 */
	private byte[] fromHex(String hex) {
		int len = hex.length();
		byte[] data = new byte[len / 2];
		for (int i = 0; i < len; i += 2) {
			data[i / 2] = (byte) ((Character.digit(hex.charAt(i), 16) << 4) + Character.digit(hex.charAt(i + 1), 16));
		}
		return data;
	}
}
